language: php

php:
  - 7.2

before_script:
  - composer install --no-interaction --prefer-source
  - echo 'APP_KEY=' > .env && php artisan key:generate
  - echo '{"/assets/app/css/app.css":"/dummy","/assets/app/js/app.js":"/dummy"}' > public/mix-manifest.json

script:
  - vendor/bin/phpunit --coverage-clover storage/logs/clover.xml

after_success:
  - travis_retry vendor/bin/php-coveralls -v
