name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, pdo, pdo_mysql, xml, ctype, json, bcmath, curl
        coverage: none

    - name: Shut down MySQL server
      run: sudo service mysql stop

    # Using MariaDB instead of MYSQL since it breaks the TickTest
    - name: Set up MariaDB
      uses: getong/mariadb-action@v1.1
      with:
        mariadb version: '10.11'
        mysql database: opendominion
        mysql user: opendominion-user
        mysql password: opendominion-password

    - name: Install PHP dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Setup .env file
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Create dummy mix-manifest.json file
      run: echo '{"/assets/app/css/app.css":"/dummy","/assets/app/js/app.js":"/dummy"}' > public/mix-manifest.json

    - name: Wait for MySQL
      run: sleep 10

    - name: Run database migrations
      run: php artisan migrate

    - name: Seed database
      run: php artisan db:seed

    - name: Sync game data
      run: php artisan game:data:sync

    - name: Run tests
      run: vendor/bin/phpunit
